// shop-react/src/ProductCatalogComponent.js
import React, { Component } from 'react';
import ProductItemComponent from './ProductItemComponent.js'
import { Grid, Row, Col } from 'react-bootstrap';
import Session from './model/Session';
import Product from './model/Product';

class ProductCatalogComponent extends Component {

  constructor(props) {
    super(props);

    this.state = {
      dataSourceReady: false,
      productsToDisplay: [],
      products: []
    };

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(event) {

    const searchingText = event.target.value;

    if (searchingText.length > 0) {

      const productsToDisplay = this.state.products.filter(
        product => product.name.toLowerCase().indexOf(searchingText.toLowerCase()) >= 0
      )

      this.setState({
        productsToDisplay: productsToDisplay
      });

    } else {

      this.setState({
        productsToDisplay: this.state.products
      });

    }

  }

  componentDidMount() {

    this.performGetProducts()

  }

  performGetProducts() {

    var session = Session.getInstance();

    var headers = {
      'Authorization': 'Kinvey ' + session.user.token,
      'X-Kinvey-API-Version': '3'
    };

    fetch("https://baas.kinvey.com/appdata/kid_ryL78U7WM/products", {
      method: 'get',
      headers: headers
    }).then(response => response.json())
      .then(responseJson => {

        console.log(responseJson);

        if (responseJson.error) {

          alert('error');

        } else {

          var products = [];
          responseJson.forEach(element => {

            var product = new Product();
            product.id = element._id;
            product.name = element.name;
            product.image = element.image;
            product.price = element.price;
            product.stock = element.stock;

            products.push(product);

          });

          this.setState({
            dataSourceReady: true,
            products: products,
            productsToDisplay: products
          })

        }

      })
      .catch(error => {

        console.error(error);

      })
  }

  render() {

    var body;
    if (this.state.dataSourceReady) {
      
      body = [];
      
      this.state.productsToDisplay.forEach(element => {

        body.push(<Col lg={3} key={element.id}><ProductItemComponent product={element} /></Col>);

      });

    } else {
      body = <h1>Cargando...</h1>
    }

    return (

      <Grid>

        <Row>

          <Col lg={6}>

            <h1>Catálogo de productos</h1>

          </Col>

          <Col lg={6} className="text-right">
            <p>¿Qué estás buscando?</p>
            <input type="text" onChange={this.handleChange} />
          </Col>

        </Row>

        <Row>
          {body}
        </Row>

      </Grid>

    );

  }

}

export default ProductCatalogComponent;

// ShopAngular/src/app/product-catalog/product-catalog.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../model/Product';
import { ProductService } from '../product.service';
import { SessionService } from '../session.service';

@Component({
  selector: 'app-product-catalog',
  templateUrl: './product-catalog.component.html',
  styleUrls: ['./product-catalog.component.css']
})
export class ProductCatalogComponent implements OnInit {

  searchingText: string;

  products: Product[] = [];
  productsToDisplay: Product[] = this.products;

  constructor(
    private productService: ProductService,
    private sessionService: SessionService
  ) { }

  ngOnInit() {

    this.performGetProducts()

  }

  inputModified(event: any) {

    if (this.searchingText.length > 0) {
      this.productsToDisplay = this.products.filter(
        product => product.name.toLowerCase().indexOf(this.searchingText.toLowerCase()) >= 0
      )
    } else {
      this.productsToDisplay = this.products;
    }

  }

  performGetProducts() {

    console.log("buscando productos");

    this.productService.performGetProducts(this.sessionService.user.token).subscribe(
      data => {

        for (let productDic of data) {

          let product: Product = {
            id: productDic._id,
            name: productDic.name,
            image: productDic.image,
            price: productDic.price,
            stock: productDic.stock
          };

          this.products.push(product);

        }

        this.productsToDisplay = this.products

      },
      error => {

        alert("Ocurrió un error al consultar el catálogo de productos");

      }
    );

  }

}
